<?php

/**
 * @file
 * Handles the creation/display of islandora:sp-pdf objects.
 */

/**
 * Implements hook_theme().
 */
function islandora_pathway_theme($existing, $type, $theme, $path) {
  // TODO: Add a "pathway" theme that renders the children, menu, etc.
  return array(
    'pathway_manage_waypoints' => array(
      'render element' => 'form',
    ),
    'islandora_pathway_object' => array(
      'variables' => array('object' => NULL),
      'template' => 'theme/pathway-object',
      'file' => 'theme/pathway_object.theme.inc',
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_pathway_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_pathway');
  // Pathway Content Model.
  $pathway_content_model = $connection->repository->constructObject('islandora:pathwayCModel');
  $pathway_content_model->owner = 'fedoraAdmin';
  $pathway_content_model->label = 'Pathway Content Model';
  $pathway_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $pathway_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pathway_ds_composite_model.xml", FALSE);
  $pathway_content_model->ingestDatastream($datastream);
  // Pathways Collection.
  $pathway_collection = $connection->repository->constructObject('islandora:sp_pathway_collection');
  $pathway_collection->owner = 'fedoraAdmin';
  $pathway_collection->label = 'Pathway Collection';
  $pathway_collection->models = 'islandora:collectionCModel';
  $pathway_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $pathway_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pathway_collection_policy.xml", FALSE);
  $pathway_collection->ingestDatastream($datastream);
  return array(
    'islandora_pathway' => array(
      'title' => 'Islandora Pathway',
      'objects' => array(
        $pathway_content_model,
        $pathway_collection,
      ),
    ),
  );
}


/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_pathway_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_pathway');
  return array(
    'Pathway Dublin Core form' => array(
      'form_file' => "$module_path/xml/islandora_pathway_DC_form.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_pathway_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_pathway_dc_form' => array(
      'content_model' => 'islandora:pathwayCModel',
      'form_name' => 'Pathway Dublin Core form',
      'dsid' => 'DC',
      'title_field' => array('dc-title'),
      'transform' => 'No transform',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_pathway_menu() {

  return array(
    'islandora/object/%islandora_object/manage/pathway' => array(
      'title' => 'Pathway',
      'page callback' => 'islandora_pathway_manage_object',
      'page arguments' => array(2),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/manage_pathway.inc',
      'access callback' => 'islandora_pathway_manage_access',
      'access arguments' => array(2),
    ),
  );
}

/**
 * Determine whether or not to show this modules manage tab.
 *
 * @param AbstractObject $object
 *   The object being managed.
 *
 * @return bool
 *   TRUE if it should be shown, and FALSE if it should not be shown.
 */
function islandora_pathway_manage_access($object = NULL) {
  $is_a_pathway = in_array('islandora:pathwayCModel', $object->models) ? TRUE : FALSE;
  return $is_a_pathway;
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_pathway_islandora_pathwayCModel_islandora_view_object($object) {
  $output = theme('islandora_pathway_object', array('object' => $object));
  return array('' => $output);
}