<?php

/**
 * @file
 * Handles the creation/display of islandora:sp-pdf objects.
 */

/**
 * Implements hook_theme().
 */
function islandora_pathway_theme($existing, $type, $theme, $path) {
  // TODO: Add a "pathway" theme that renders the children, menu, etc.
  return array();
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_pathway_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_pathway');
  // Pathway Content Model.
  $pathway_content_model = $connection->repository->constructObject('islandora:pathwayCModel');
  $pathway_content_model->owner = 'fedoraAdmin';
  $pathway_content_model->label = 'Pathway Content Model';
  $pathway_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $pathway_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pathway_ds_composite_model.xml", FALSE);
  $pathway_content_model->ingestDatastream($datastream);
  // Pathways Collection.
  $pathway_collection = $connection->repository->constructObject('islandora:sp_pathway_collection');
  $pathway_collection->owner = 'fedoraAdmin';
  $pathway_collection->label = 'Pathway Collection';
  $pathway_collection->models = 'islandora:collectionCModel';
  $pathway_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $pathway_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pathway_collection_policy.xml", FALSE);
  $pathway_collection->ingestDatastream($datastream);
  return array(
    'islandora_pathway' => array(
      'title' => 'Islandora Pathway',
      'objects' => array(
        $pathway_content_model,
        $pathway_collection,
      ),
    ),
  );
}


